name: GitHub Actions Demo
run-name: ${{ github.actor }} and  is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} and ${{ secrets.MY_NAME }} event."
      - run: |
            echo '{ "name" : "munir"}' >> props.json
            cat props.json
            git config --global user.name ${{ github.actor }}
            git config --global user.email ${{ github.actor }}@users.noreply.github.com
            git add props.json
            git commit -m "updating sate-- props.json"
            git push

